# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bikeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeId', models.CharField(max_length=50)),
                ('bikeIp', models.CharField(max_length=50)),
            ],
        ),
    ]
