# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bikeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeIp', models.CharField(max_length=50)),
                ('bikeStatus', models.BooleanField(default=0)),
                ('bikePort', models.CharField(default=18000, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bikeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeLongitude', models.FloatField()),
                ('bikeLatitude', models.FloatField()),
                ('bikeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.bikeData')),
            ],
        ),
        migrations.CreateModel(
            name='travelDetail',
            fields=[
                ('detailId', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.TimeField(auto_now_add=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='userInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=50)),
                ('userSex', models.BooleanField(default=1)),
                ('creditLevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userTravel',
            fields=[
                ('travelId', models.AutoField(primary_key=True, serialize=False)),
                ('openTime', models.TimeField(auto_now_add=True)),
                ('endTime', models.TimeField(null=True)),
                ('lockStatus', models.BooleanField(default=0)),
                ('bikeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.bikeData')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.userInfomation')),
            ],
        ),
        migrations.AddField(
            model_name='traveldetail',
            name='travelId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.userTravel'),
        ),
    ]
