# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bikeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeCountry', models.CharField(max_length=50)),
                ('bikeProvince', models.CharField(max_length=50)),
                ('bikeCity', models.CharField(max_length=50)),
                ('bikeDistrict', models.CharField(max_length=50)),
                ('bikeLongitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('bikeLatitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('bikeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.bikeData')),
            ],
        ),
    ]
