# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_bikelocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikedata',
            name='bikeId',
        ),
    ]
