# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_remove_bikedata_bikeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikelocation',
            name='bikeLatitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bikelocation',
            name='bikeLongitude',
            field=models.FloatField(),
        ),
    ]
