# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='travelDetial',
            fields=[
                ('detailId', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.TimeField(auto_now=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='userTravel',
            fields=[
                ('travelId', models.AutoField(primary_key=True, serialize=False)),
                ('openTime', models.TimeField(auto_now_add=True)),
                ('travelTimeRange', models.TimeField(null=True)),
                ('travelStart', models.CharField(max_length=128)),
                ('travelEnd', models.CharField(max_length=128)),
                ('lockStatus', models.BooleanField(default=0)),
                ('bikeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.bikeData')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='usertravel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.userInfo'),
        ),
        migrations.AddField(
            model_name='traveldetial',
            name='travelId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.userTravel'),
        ),
    ]
