# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_auto_20180308_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertravel',
            name='nums',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
