# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_remove_usertravel_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userId',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
