# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_auto_20180308_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userId',
            field=models.CharField(max_length=128),
        ),
    ]
