# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0017_auto_20180308_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfomation',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfomation',
            name='userId',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
