# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0018_auto_20180308_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikedata',
            name='bikePort',
            field=models.CharField(default=10000, max_length=10),
        ),
        migrations.AddField(
            model_name='bikedata',
            name='bikeStatus',
            field=models.BooleanField(default=0),
        ),
    ]
