# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0019_auto_20180414_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedata',
            name='bikePort',
            field=models.CharField(default=18000, max_length=10),
        ),
    ]
